name: Publish docker images

on:
  push:
    branches: ["master"]
    
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build and push image without xdebug
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            no-cache=true
          tags: | 
            softavis/symfony-cli:latest
